name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t online_test-web .

      - name: Run Docker container
        run: |
          docker run -d --name django_app1 online_test-web
          sleep 10  # Give the app time to initialize

      #  Apply Django migrations
      - name: Apply Django migrations
        run: |
          docker exec django_app1 python manage.py migrate

      - name: Run tests
        run: |
          docker exec django_app1 pytest accounts/tests.py || (
            echo "Tests failed. Container logs:"
            docker logs django_app1
            exit 1
          )

      - name: Stop and remove Docker container
        if: always()
        run: |
          docker stop django_app1
          docker rm django_app1

  deploy_koyeb:
    runs-on: ubuntu-latest
    needs: build  # This job will only run if the 'build' job succeeds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Koyeb CLI
        run: |
          curl -sSL https://github.com/koyeb/koyeb-cli.git | tar -xz -C /usr/local/bin
          koyeb version

      - name: Deploy to Koyeb
        env:
          KOYEB_API_KEY: ${{ secrets.TestTryKey }}
        run: |
          koyeb login --api-key $TestTryKey
          koyeb app deploy --app ${shop} --source .